server:
  port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        transactionConsumer-in-0:
          binder: kafka
          destination: transactions-topic
          content-type: application/x-protobuf
        approvedTransactionProducer-out-0:
          binder: kafka
          destination: approved-transactions-topic
          content-type: application/x-protobuf
        invalidTransactionProducer-out-0:
          binder: kafka
          destination: approved-transactions-topic
          content-type: application/x-protobuf

